#include "Gctrack.h"

void ReadTree2()
{
   //read the Tree generated by ReadTree2 and fill one histogram
   //we are only interested by the destep branch.
     
   //note that we use "new" to create the TFile and TTree objects !
   //because we want to keep these objects alive when we leave 
   //this function.
   TFile *f = new TFile("tree2.root");

   // Get the TTree from file
   TTree *t2 = (TTree*)f->Get("t2");

   // Connect a object of class Gctrack with the tree    
   Gctrak *gstep = NULL;
   t2->SetBranchAddress("track",&gstep);

   // Get pointer to defined branch
   TBranch *b_destep = t2->GetBranch("destep");
   
   //create one histogram
   TH1F *hdestep   = new TH1F("hdestep","destep in Mev",100,1e-5,3e-5);
   
   //read only the destep branch for all entries
   Long64_t nentries = t2->GetEntries();
   for (Long64_t i=0;i<nentries;i++) {
      b_destep->GetEntry(i); 
      hdestep->Fill(gstep->destep);
   }
  
   //we do not close the file. 
   //We want to keep the generated histograms
   //We fill a 3-d scatter plot with the particle step coordinates
   TCanvas *c1 = new TCanvas("c1","c1",600,800);
   c1->SetFillColor(42);
   c1->Divide(1,2);
   c1->cd(1);
   hdestep->SetFillColor(45);
   hdestep->Fit("gaus");
   c1->cd(2);
   gPad->SetFillColor(37);
   t2->SetMarkerColor(kRed);

   // Draw a three dimensional histogram plotting the positions
   // of the particles for each step
   // In the end you will see the particle tracks
   t2->Draw("vect[0]:vect[1]:vect[2]");
   if (gROOT->IsBatch()) return;
   
   // invoke the OpenGL viewer
   gPad->GetViewer3D("ogl");
}   
